server:
  server-address: https://repick.seoul.kr
  server-develop-address: https://repick-dev.store
  servlet:
    context-path: /api
logging:
  slack:
    webhook-uri: ${SLACK_ERROR_WEBHOOK_URI}
    config: classpath:logback-spring.xml
webhook:
  sell-order-uri: ${SLACK_SELL_ORDER_URI}
  order-uri: ${SLACK_ORDER_URI}
  expense-settlement-uri: ${SLACK_EXPENSE_SETTLEMENT_URI}
sweet-tracker:
  api-key: ${SWEET_TRACKER_API_KEY}