spring:
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: repick-s3-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false