name: Deploy Production Server

on:
  push:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar


      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/repick-web .
          docker push ${{ secrets.DOCKER_REPO }}/repick-web
          docker build -f dockerfile-nginx -t repick/repick-nginx .
          docker push repick/repick-nginx

      ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/srv/ubuntu/
            sudo chmod 666 /var/run/docker.sock
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/repick-web
            sudo docker pull ${{ secrets.DOCKER_REPO }}/repick-nginx
            docker-compose -f docker-compose-develop.yaml --env-file /home/ubuntu/srv/ubuntu/.env up -d
            docker image prune -f